### ISSUE TITLE
Invalid Variable 

### ISSUE THREAD

**Issue by wiseflat** [Nodejs-XPL/xpl-api#2]
Hello,

Maybe I am wrong but it seems that this variable was not declared correctly :

```
this.configuration.forceBodySchemaValidation
```

It should be :

```
this._configuration.forceBodySchemaValidation
```

Once I corrected it, schema was correctly validated

https://github.com/Nodejs-XPL/xpl-api/blob/master/lib/xpl-api.js#L586

**Comment by oeuillot** [comment]
Fix in version 1.0.14
