### ISSUE TITLE
Prise en charge des champs du header dans les trames xPL

### ISSUE THREAD

**Issue by wiseflat** [Nodejs-XPL/xpl-api#3]
Bonjour Olivier,

En xpl on a la possibilité de pouvoir adresser un message xpl-cmnd à une source via le champs : « target » 

Je te donne un example via la commande native du projet xpl-perl :

```
xpl-sender -m xpl-cmnd -c email.config -t bnz-email.wiseflat version=0.1.0 enable=false user=aaa password=bbb host=xxx.sss.zzz ssl=true
```

J'ai construit des schémas de configuration pour mes passerelles mais tu peux imaginer avoir plusieurs CM15 x10, ou dongle zwave / xPL et vouloir cibler le pilotage d'une lampe sur tel cible sans que les autres ne la traite.

Voici ce que j’ai dans le logger

Le détail de ma commande (tu retrouves la passerelle qui émet et à qui elle destine le message : bnz-sender.wiseflat -> bnz-email.wiseflat) :

```
172.16.2.8:40061 [xpl-cmnd/email.config: bnz-sender.wiseflat -> bnz-email.wiseflat 0.1.0/false/aaa/bbb/xxx.sss.zzz/true]
email.config
{
version=0.1.0
enable=false
user=aaa
password=bbb
host=xxx.sss.zzz
ssl=true
}
```

Et voici l’acquittement de ma passerelle bnz-email.wiseflat qui s’adresse à la cible « * » mais qui pourrait tout aussi bien pouvoir répondre à bnz-sender.wiseflat 

```
172.16.2.8:40061 [xpl-stat/email.config: bnz-email.wiseflat -> * 0.1.0/false/aaa/bbb/xxx.sss.zzz/true]
email.config
{
version=0.1.0
enable=false
user=aaa
password=bbb
host=xxx.sss.zzz
ssl=true
}
```

Chacune de mes passerelles regarde le détail des trames qui les concernent (en fonction du schéma) si la target correspond à leur nom de source xPL (options.xplSource)
Si c’est le cas, elle traite le message et répond par un acquittement (via xpl-stat). Comme présenté au dessus .

Voici le message complet au format JSON

```
{"headerName":"xpl-stat","header":{"hop":"1","source": "bnz-sender.wiseflat","target":"bnz-email.wiseflat"},"bodyName":"email.config","source":"bnz-email.wiseflat","body":{"version":"0.1.0","enable":true,"user":"qqq","password":"bbb","host":"xxx.sss.zzz","ssl":true}} 
```

Je n’ai pas l’impression que tu en ai eu besoin jusqu’ici.
Serait-ce possible de faire un petite évolution ?

A priori les 3 fonctions visées sont : sendXplStat, sendXplTrig, sendXplCmnd

Merci d'avance pour cette fonctionnalité

**Comment by oeuillot** [comment]
Can you test:
https://github.com/Nodejs-XPL/xpl-api/commit/c48824313cb86c596a08b8a86be489eda5ad1d4f

**Comment by oeuillot** [comment]
Done
